_parent_: configs/shapenet/base.yaml

group: reconstruction_stage_two
name: 
load: 
load_deformnet:
mean_latent:
evaluation:
is_stage_two_active: true
eval_split:

arch:
    enc_network: resnet18
    enc_pretrained: true

camera:
    model: orthographic
    dist: 2.5

data:
    dataset: pix3d_pascal3d
    num_workers: 4
    bgcolor: 1
    pix3d:
        set: imagenet
        cat: chair
    pascal3d:
        cat: chair

impl:
    sdf_samples: 5
    depth_range: [1.2,3.8]
    importance: true
    srn_steps: 20
    rand_sample: 2048
    init_depth: 1.2
    bisection_steps: 10

loss_weight:
    render: 1
    shape_silh: 3 #change to 1 for airplane
    ray_intsc: 3 #change to 1 for chair
    ray_free: 0.1
    eikonal: 0.1
    pts_deformations: 0.01
    symmetry_loss: 1

optim:
    lr: 1.e-4
    
max_epoch: 60

freq:
    scalar: 200 # iterations
    vis: 1000 # iterations
    eval: 1 # epochs
    ckpt: 2 # epochs
    ckpt_latest: 2000 # iterations