_parent_: configs/shapenet/base.yaml

group: reconstruction_stage_one
name: 
load: output/shapenet/pretrain_sdf_generator/shapenet/latest.ckpt
load_deformnet:
mean_latent:
is_stage_two_active:
eval_split:

arch:
    enc_network: resnet18
    enc_pretrained: true


data:
    dataset: shapenet
    num_workers: 4
    bgcolor: 1
    shapenet:
        cat:
        train_view:
        test_view: 1

impl:
    sdf_samples: 5
    depth_range: [2,3.5]
    importance: true
    srn_steps: 10
    rand_sample: 1024
    init_depth: 2
    bisection_steps: 10

loss_weight:
    render: 1
    shape_silh: 1
    ray_intsc: 3
    ray_free: 0.1
    eikonal: 0.01
    pts_deformations: 0

optim:
    lr: 1.e-4
    
max_epoch: 60

freq:
    scalar: 200 # iterations
    vis: 1000 # iterations
    eval: 1 # epochs
    ckpt: 2 # epochs
    ckpt_latest: 2000 # iterations